### ISSUE TITLE
Force setting of names before payment for general release

### ISSUE THREAD

**Issue by Edisach** [toastwaffle/KebleBall#166]
1. Change the redirect from reservation to dashboard instead of payment
2. Flash a message on the dash if there are tickets with unset names to set them before payment
3. Only populate the payment page with tickets with names

**Comment by Edisach** [comment]
Branch forceNames has 1 commit initially solving this. Possible issues:
1. All payment methods redirect to the dash, not the individual pages - this might be an issue for battels or cash/cheque?
2. battels and cash/cheque do not currently force the user to name tickets.

**Comment by toastwaffle** [comment]
Battels should behave in the same way (not showing the tickets on the
confirm battels page until the name has been set)

For cash/cheque, we'll have to remind the Treasurer not to mark things as
paid until the name is set.

Should probably flash a different message based on the payment method?

**Comment by Edisach** [comment]
I'm not sure it's necessary to flash a different message for each payment method. It might be worth rewriting the existing message for its new location?

**Comment by toastwaffle** [comment]
Maybe we should change the "Confirm battels payment"/"Complete card payment" buttons to just read something like "Complete Payment", and then the flashed message can read "You must set a name on your tickets before they can be paid for. Please set names on your tickets, and then click the 'Complete Payment' button"

**Comment by toastwaffle** [comment]
Fixed
